### ISSUE TITLE
Can't get 2 augmentations

### ISSUE THREAD

**Issue by Dayyer1** [KryptonCaptain/Thaumic-Dyes#8] opened 2017-05-20 17:15 UTC
I can't get 2 different augmentations on one piece of enhanced runic armor, but I can get 2 of the same augmentation on one.
I tried right-clicking the pieces, but that didn't seem to do anything.

**Comment by KryptonCaptain** [comment] 2017-05-21 03:41
You have to right-click the piece against a block to swap augment position, it's a little unintuitive, I know.

Can you explain/list the process you were using to add 2 of the same augment, and for trying 2 different augments? (Seems obvious, but I have to ask)

**Comment by Dayyer1** [comment] 2017-05-21 14:59
Hold on, I figured it out. I did just have to right click a block... oops.
When I applied the 2 same augments, I just applied them without right-clicking on a block. (Or at least, I didn't notice right-clicking on one.) When I put on two different augments, I applied one right after the other, without right-clicking a block. Is it possible to make the 2nd augment automatically fill up the next augmentation slot? I think if people accidentally keep rewriting augments without knowing to right-click a block, it'll get them pretty frustrated, especially without a way to cheat-in items.

**Comment by KryptonCaptain** [comment] 2017-05-22 00:46
Given the mess that already is the augment recipe code, probably not...
Also, you would have had to have clicked a block - the recipe adds a data tag to the first slot only ( {upgrade:#} )

It's on my list to go over the runic entries anyway.
Closing, because not a bug

**Closed as completed by KryptonCaptain** 2017-05-22 00:46 UTC
